"""
Unit tests for audio_player.py
Tests logic and file resolution — does not play actual audio.
Run with: python -m pytest tests/
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import pytest
from unittest.mock import patch, MagicMock
from audio_player import (
    _get_sample_path,
    get_available_notes,
    NOTE_TO_FILE,
    SAMPLES_DIR,
)


class TestGetSamplePath:
    def test_valid_note_returns_path(self):
        path = _get_sample_path('C')
        assert path.endswith('C.wav')
        assert SAMPLES_DIR in path

    def test_sharp_note_returns_correct_filename(self):
        path = _get_sample_path('C#')
        assert 'C_sharp.wav' in path

    def test_invalid_note_raises_value_error(self):
        with pytest.raises(ValueError, match="Unknown note"):
            _get_sample_path('Z')

    def test_missing_file_raises_file_not_found(self):
        with patch('os.path.exists', return_value=False):
            with pytest.raises(FileNotFoundError, match="Sample not found"):
                _get_sample_path('C')

    def test_all_12_notes_have_valid_mappings(self):
        from swara_mapper import SEMITONES
        for note in SEMITONES:
            assert note in NOTE_TO_FILE, f"{note} missing from NOTE_TO_FILE"


class TestGetAvailableNotes:
    def test_returns_list(self):
        result = get_available_notes()
        assert isinstance(result, list)

    def test_all_notes_available_when_samples_exist(self):
        # All samples should be generated by download_samples.py
        result = get_available_notes()
        assert len(result) == 12

    def test_returns_empty_when_no_samples(self):
        with patch('os.path.exists', return_value=False):
            result = get_available_notes()
            assert result == []


class TestPlayFunctions:
    """Test play functions with pygame mocked out."""

    @patch('audio_player.pygame')
    @patch('audio_player._initialized', True)
    def test_play_note_loads_correct_file(self, mock_pygame):
        mock_sound = MagicMock()
        mock_sound.get_length.return_value = 0.01
        mock_pygame.mixer.Sound.return_value = mock_sound

        from audio_player import play_note
        play_note('A', wait=False)

        call_args = mock_pygame.mixer.Sound.call_args[0][0]
        assert 'A.wav' in call_args
        mock_sound.play.assert_called_once()

    @patch('audio_player.pygame')
    @patch('audio_player._initialized', True)
    def test_stop_all_calls_mixer_stop(self, mock_pygame):
        from audio_player import stop_all
        stop_all()
        mock_pygame.mixer.stop.assert_called_once()

    @patch('audio_player.pygame')
    @patch('audio_player._initialized', True)
    def test_is_playing_returns_bool(self, mock_pygame):
        mock_pygame.mixer.get_busy.return_value = False
        from audio_player import is_playing
        result = is_playing()
        assert isinstance(result, bool)
